name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  JAVA_VERSION: "17"
  FLUTTER_VERSION: "3.35.4"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: false
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
      
    - name: Build release APK
      run: flutter build apk --release
      
    - name: Build release AAB
      run: flutter build appbundle --release
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          ## Changes in this Release
          
          - Built from commit ${{ github.sha }}
          - APK and AAB files available for download
          
          ## Installation
          
          ### From APK
          1. Download the APK file below
          2. Enable "Install from Unknown Sources" in Android settings
          3. Install the APK
          
          ### From F-Droid (coming soon)
          - Will be available on F-Droid store
          
    - name: Upload Release APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: monica-mobile-app-${{ github.ref_name }}.apk
        asset_content_type: application/vnd.android.package-archive
        
    - name: Upload Release AAB
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/bundle/release/app-release.aab
        asset_name: monica-mobile-app-${{ github.ref_name }}.aab
        asset_content_type: application/octet-stream